services:

  app:
    container_name: avatar48_landing
    restart: always
    image: 457442647158.dkr.ecr.ap-northeast-1.amazonaws.com/avatar48/dev/avatar48_landing
    command: ["npm", "run", "start"]
    ports:
      - $PORT:3030
    networks:
      - avatar48_network

networks:
  avatar48_network:
    driver: bridge