services:

  app:
    container_name: ai_avatar_landingpage
    restart: always
    image: 023889582722.dkr.ecr.ap-northeast-1.amazonaws.com/ai-avatar/staging/ai-avatar-landingpage
    command: ["npm", "start"]
    ports:
      - $PORT:3030
    networks:
      - airstage

volumes:
  market_ai_agent_volume:
    external: true

networks:
  airstage:
    driver: bridge